### ISSUE TITLE
Driver outputs invalid GPSFix message when fix is invalid

### ISSUE THREAD

**Issue by kriskozak** [swri-robotics/swiftnav_piksi#8]
It appears that the driver outputs a GPSFix message (that appears to be just an uninitialized GPSFix message with the status of the fix set to -1/STATUS_NO_FIX) when a measurement is unavailable (reported as fix_description: Invalid in the native Piksi messages). Our preferred method is to suppress the message when there is not a valid measurement to report.

**Comment by pjreed** [comment]
If we want to suppress this, I'd rather add a parameter to do so rather than cut it out entirely.  In my experience with other GPS drivers, being able to get GPSFix messages with a STATUS_NO_FIX is useful when you're trying to debug connectivity issues.

**Comment by kriskozak** [comment]
While I'm not 100% certain, I think that all of the drivers that publish GPSFix messages that we use do suppress invalid messages. Which GPS drivers publish GPSFix messages no matter what? For debugging connectivity issues, I recommend using the other messages published by the various drivers (including this one).

**Comment by pjreed** [comment]
The Microstrain driver always publishes them, and I *think* the NovAtel SPAN driver also publishes them.

**Comment by kriskozak** [comment]
For what it's worth, I would prefer in both of those cases to suppress the GPSFix messages by default.  I'm not sure that all downstream components handle invalid messages correctly (or at least I don't recall doing anything special to detect and handle invalid messages, although that's never a bad idea), and I don't think that it's unreasonable to require a GPSFix message to contain valid data.

**Comment by pjreed** [comment]
Since there's a flag specifically to indicate that the fix is invalid, I don't think it's unreasonable to expect that a GPSFix could contain invalid data. :wink:  I actually fixed a bug in `swri_transform_util` recently where `initialize_origin.py` was ruining everything forever if the first fix it received was invalid.

**Comment by kriskozak** [comment]
There are a number of issues with the GPSFix message (though I greatly prefer it to the NavSatFix plus Odometry message convention), and that is one of them (the rest of the fields in the status are not much better).  Because it is a generic GPS message, there is no additional information conveyed beyond "this message is invalid," which can also be conveyed by simply not sending it.  I'll concede that it's a good idea to handle invalid messages, but I also think that we should be producing them in the drivers that we control.
